# Generated by Django 4.2.7 on 2023-11-09 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user_id",
        ),
    ]
